import { type Booking, type Room, type RoomType, type VisitPackage } from './types';

export const initialVisitPackages: VisitPackage[] = [
  {
    id: 'vp1',
    name: 'Morning Half-Day',
    type: 'half-day',
    description: "A refreshing half-day experience through Sumiran's lush forest trails with a guided walk, one activity of choice, and light refreshments.",
    duration: '4 hours',
    pricePerPerson: 1499,
    includedActivities: 1,
    activities: ['Bird Watching', 'Nature Walk', 'Butterfly Garden', 'Forest Photography'],
    includes: ['Forest Guide', 'Refreshments', 'Welcome Drink', 'Activity Kit'],
    maxGroupSize: 20,
    isActive: true,
    timing: '6:00 AM – 10:00 AM',
  },
  {
    id: 'vp2',
    name: 'Afternoon Half-Day',
    type: 'half-day',
    description: "An immersive afternoon session exploring the resort's hidden trails, ending with a forest sunset experience.",
    duration: '4 hours',
    pricePerPerson: 1499,
    includedActivities: 1,
    activities: ['Jungle Safari', 'Zip-Lining', 'Kayaking', 'Sunset Trek'],
    includes: ['Forest Guide', 'Refreshments', 'Safety Gear', 'Activity Kit'],
    maxGroupSize: 15,
    isActive: true,
    timing: '2:00 PM – 6:00 PM',
  },
  {
    id: 'vp3',
    name: 'Full Day Forest Escape',
    type: 'full-day',
    description: 'A complete day immersed in nature — from sunrise jungle safari to an evening bonfire, with all meals and two activities included.',
    duration: '10 hours',
    pricePerPerson: 2999,
    includedActivities: 2,
    activities: ['Jungle Safari', 'Bird Watching', 'Zip-Lining', 'Nature Walk', 'Kayaking', 'Rock Climbing'],
    includes: ['Forest Guide', 'Breakfast', 'Lunch', 'Evening Snacks', 'Safari Vehicle', 'Activity Kit'],
    maxGroupSize: 25,
    isActive: true,
    timing: '6:00 AM – 5:00 PM',
  },
  {
    id: 'vp4',
    name: 'Premium Full Day',
    type: 'full-day',
    description: 'An exclusive full-day premium package with personalised itinerary, gourmet meals, and unlimited access to all resort activities.',
    duration: '10 hours',
    pricePerPerson: 4999,
    includedActivities: 3,
    activities: ['Jungle Safari', 'Bird Watching', 'Zip-Lining', 'Kayaking', 'Ayurvedic Spa', 'Rock Climbing', 'Night Trek'],
    includes: ['Personal Guide', 'Gourmet Breakfast', 'Gourmet Lunch', 'Spa Session', 'All Activities', 'Bonfire Evening'],
    maxGroupSize: 10,
    isActive: false,
    timing: '6:00 AM – 5:00 PM',
  },
  {
    id: 'vp5',
    name: 'Quick Forest Dip',
    type: 'short-visit',
    description: 'A short but memorable forest experience — perfect for those passing through. Includes a guided trail walk and scenic photo stops.',
    duration: '2 hours',
    pricePerPerson: 699,
    includedActivities: 0,
    activities: ['Forest Photography', 'Butterfly Garden', 'Scenic Trail Walk'],
    includes: ['Forest Guide', 'Welcome Drink', 'Photography Spots'],
    maxGroupSize: 30,
    isActive: true,
    timing: 'Flexible (9 AM / 11 AM / 3 PM slots)',
  },
];

export const initialRoomTypes: RoomType[] = [
  {
    id: 'rt1',
    name: 'Deluxe Room',
    description: 'Comfortable rooms with forest-facing balcony and modern amenities perfect for couples or solo travelers.',
    basePrice: 6999,
    maxOccupancy: 2,
    baseOccupancy: 2,
    extraPersonPrice: 1000,
    amenities: ['AC', 'Wi-Fi', 'Forest View', 'Balcony', 'Mini Bar', 'Room Service'],
    totalRooms: 8,
    isSingleOccupancy: false,
  },
  {
    id: 'rt2',
    name: 'Premium Suite',
    description: 'Spacious suites with a separate living area, premium furnishings, and a panoramic jungle view.',
    basePrice: 11999,
    maxOccupancy: 3,
    baseOccupancy: 2,
    extraPersonPrice: 1200,
    amenities: ['AC', 'Wi-Fi', 'Panoramic View', 'Living Area', 'Jacuzzi', 'Butler Service', 'Mini Bar'],
    totalRooms: 5,
    isSingleOccupancy: false,
  },
  {
    id: 'rt3',
    name: 'Forest Villa',
    description: 'Private standalone villas nestled in the forest, offering ultimate seclusion and nature immersion.',
    basePrice: 18999,
    maxOccupancy: 4,
    baseOccupancy: 2,
    extraPersonPrice: 1500,
    amenities: ['AC', 'Wi-Fi', 'Private Pool', 'Outdoor Shower', 'Bonfire Area', 'Butler Service', 'Kitchenette'],
    totalRooms: 4,
    isSingleOccupancy: false,
  },
  {
    id: 'rt4',
    name: 'Royal Cottage',
    description: 'Heritage-inspired cottages with traditional decor, premium comfort, and curated royal experiences.',
    basePrice: 24999,
    maxOccupancy: 6,
    baseOccupancy: 2,
    extraPersonPrice: 1800,
    amenities: ['AC', 'Wi-Fi', 'Private Garden', 'Plunge Pool', 'Dining Pavilion', 'Personal Chef', 'Concierge'],
    totalRooms: 2,
    isSingleOccupancy: false,
  },
];

export const initialRooms: Room[] = [
  { id: 'r1', roomTypeId: 'rt1', roomNumber: '101', floor: 1, status: 'available', view: 'Forest East' },
  { id: 'r2', roomTypeId: 'rt1', roomNumber: '102', floor: 1, status: 'occupied', view: 'Forest West' },
  { id: 'r3', roomTypeId: 'rt1', roomNumber: '201', floor: 2, status: 'available', view: 'Forest East' },
  { id: 'r4', roomTypeId: 'rt1', roomNumber: '202', floor: 2, status: 'maintenance', view: 'Garden' },
  { id: 'r5', roomTypeId: 'rt2', roomNumber: '301', floor: 3, status: 'occupied', view: 'Panoramic North' },
  { id: 'r6', roomTypeId: 'rt2', roomNumber: '302', floor: 3, status: 'available', view: 'Panoramic South' },
  { id: 'r7', roomTypeId: 'rt3', roomNumber: 'V01', floor: 0, status: 'available', view: 'Private Forest' },
  { id: 'r8', roomTypeId: 'rt3', roomNumber: 'V02', floor: 0, status: 'occupied', view: 'Lakeside Forest' },
  { id: 'r9', roomTypeId: 'rt4', roomNumber: 'RC01', floor: 0, status: 'available', view: 'Royal Garden' },
  { id: 'r10', roomTypeId: 'rt4', roomNumber: 'RC02', floor: 0, status: 'occupied', view: 'Heritage Garden' },
];

export const initialBookings: Booking[] = [
  {
    id: 'BK001',
    bookingType: 'stay',
    guestName: 'Arjun Mehta',
    guestEmail: 'arjun.mehta@email.com',
    guestPhone: '+91 98765 43210',
    guests: 2,
    status: 'confirmed',
    paymentStatus: 'paid',
    totalAmount: 23997,
    paidAmount: 23997,
    createdAt: '2026-02-20',
    roomId: 'r1',
    roomTypeId: 'rt1',
    checkIn: '2026-03-05',
    checkOut: '2026-03-08',
    nights: 3,
    activities: ['Jungle Safari', 'Bird Watching'],
    specialRequests: 'Late check-in around 10 PM. Need a quiet room.',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'BK002',
    bookingType: 'day-visit',
    guestName: 'Priya Sharma',
    guestEmail: 'priya.s@email.com',
    guestPhone: '+91 87654 32109',
    guests: 4,
    status: 'confirmed',
    paymentStatus: 'paid',
    totalAmount: 11996,
    paidAmount: 11996,
    createdAt: '2026-02-22',
    visitDate: '2026-03-06',
    visitType: 'full-day',
    activities: ['Jungle Safari', 'Zip-Lining'],
    paymentMethod: 'UPI',
  },
  {
    id: 'BK003',
    bookingType: 'stay',
    guestName: 'Rahul Verma',
    guestEmail: 'rahul.v@email.com',
    guestPhone: '+91 76543 21098',
    guests: 2,
    status: 'checked-in',
    paymentStatus: 'paid',
    totalAmount: 35997,
    paidAmount: 35997,
    createdAt: '2026-02-18',
    roomId: 'r5',
    roomTypeId: 'rt2',
    checkIn: '2026-03-03',
    checkOut: '2026-03-06',
    nights: 3,
    activities: ['Jungle Safari', 'Night Trek'],
    paymentMethod: 'Net Banking',
  },
  {
    id: 'BK004',
    bookingType: 'stay',
    guestName: 'Sneha Kapoor',
    guestEmail: 'sneha.k@email.com',
    guestPhone: '+91 65432 10987',
    guests: 2,
    status: 'pending',
    paymentStatus: 'partial',
    totalAmount: 56997,
    paidAmount: 20000,
    createdAt: '2026-02-25',
    roomId: 'r7',
    roomTypeId: 'rt3',
    checkIn: '2026-03-15',
    checkOut: '2026-03-18',
    nights: 3,
    activities: ['Jungle Safari', 'Bird Watching', 'Zip-Lining'],
    specialRequests: 'Honeymoon package, please arrange flowers and candles.',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'BK005',
    bookingType: 'day-visit',
    guestName: 'Kiran Patel',
    guestEmail: 'kiran.p@email.com',
    guestPhone: '+91 54321 09876',
    guests: 2,
    status: 'confirmed',
    paymentStatus: 'paid',
    totalAmount: 2998,
    paidAmount: 2998,
    createdAt: '2026-02-26',
    visitDate: '2026-03-04',
    visitType: 'half-day',
    activities: ['Bird Watching'],
    paymentMethod: 'UPI',
  },
  {
    id: 'BK006',
    bookingType: 'stay',
    guestName: 'Vikram Singh',
    guestEmail: 'vikram.s@email.com',
    guestPhone: '+91 43210 98765',
    guests: 4,
    status: 'cancelled',
    paymentStatus: 'refunded',
    totalAmount: 74997,
    paidAmount: 0,
    createdAt: '2026-02-10',
    roomId: 'r9',
    roomTypeId: 'rt4',
    checkIn: '2026-02-28',
    checkOut: '2026-03-01',
    nights: 1,
    activities: ['Jungle Safari', 'Nature Walk'],
    paymentMethod: 'Credit Card',
  },
  {
    id: 'BK007',
    bookingType: 'stay',
    guestName: 'Ananya Roy',
    guestEmail: 'ananya.r@email.com',
    guestPhone: '+91 32109 87654',
    guests: 2,
    status: 'completed',
    paymentStatus: 'paid',
    totalAmount: 47998,
    paidAmount: 47998,
    createdAt: '2026-02-05',
    roomId: 'r8',
    roomTypeId: 'rt3',
    checkIn: '2026-02-20',
    checkOut: '2026-02-22',
    nights: 2,
    activities: ['Jungle Safari', 'Ayurvedic Spa'],
    paymentMethod: 'Debit Card',
  },
  {
    id: 'BK008',
    bookingType: 'day-visit',
    guestName: 'Manish Gupta',
    guestEmail: 'manish.g@email.com',
    guestPhone: '+91 21098 76543',
    guests: 6,
    status: 'pending',
    paymentStatus: 'unpaid',
    totalAmount: 17994,
    paidAmount: 0,
    createdAt: '2026-03-01',
    visitDate: '2026-03-10',
    visitType: 'full-day',
    activities: ['Jungle Safari', 'Zip-Lining'],
    specialRequests: 'Corporate group outing. Need team-building activities.',
    paymentMethod: undefined,
  },
];
