import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Urbanist } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["300","400","600","700"], // whenever tailwind class "font-semibold" or "font-bold" is used they will pick the nearest downloaded font weight text from this provided options array. By default tailwind uses font weights normal -> "400", semibold -> "600", bold -> "700". And that is why i provided the exact matching font weight texts.
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.className}`}>{children}</body>
    </html>
  );
}
